name: mentor_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  velocity_x: ^4.1.2
  http: ^0.13.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  change_app_package_name: ^1.1.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.7
  timeago: ^3.6.0
  flutter_easyloading: ^3.0.5
  intl: ^0.18.1
  google_fonts: ^4.0.4
  flutter_spinkit: ^5.2.0
  timezone: ^0.9.2
  flutter_svg: ^2.0.9
  flutter_chat_bubble: ^2.0.2
  flutter_stripe: ^10.1.1
  youtube_player_flutter: ^9.0.0
  otp_text_field: ^1.1.3
  zego_uikit_prebuilt_call: ^4.4.3
  zego_uikit_signaling_plugin: ^2.7.6
  shimmer: ^3.0.0
  zego_zimkit: ^1.17.2



dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/icons/


  uses-material-design: true

