name: mentor_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  velocity_x: ^4.1.2
  get_cli: ^1.8.4
  http: ^0.13.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  change_app_package_name: ^1.1.0
  flutter_rating_bar: ^4.0.1
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  timeago: ^3.6.0
  flutter_easyloading: ^3.0.5
  intl: ^0.18.1
  sign_in_with_apple: ^5.0.0
  google_fonts: ^4.0.4
  flutter_spinkit: ^5.2.0
  timezone: ^0.9.2


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/icons/


  uses-material-design: true

